### ISSUE TITLE
Properties and access to answer lists

### ISSUE THREAD

**Issue by mayisa87** [CapioIM/P6QuizMaker#13]
https://github.com/CapioIM/P6QuizMaker/blob/e3f2cd170b4b88e95b1b8111c6daf5979378a3cf/P6QuizMaker/Question.cs#L5-L7

Please rewatch the videos about Properties in Module 7 and use properties instead of usual public fields.

**Comment by CapioIM** [comment]
I didn't watch module 7 at all

**Comment by CapioIM** [comment]
I quickly added string as property , however not sure how to do properties for list

**Comment by mayisa87** [comment]
We discussed this also internally. So for the lists, what about having methods that do the modification part? So in general it is possible, like you tried already, to have properties also for your lists and then access the lists via property and call usual list methods Add and Remove from there.

The other option would be to implement methods in your Question class, that do exactly the things you need:

So like an "AddAnswer(string answer) that adds internally something to your list. The list itself can be private then.

Or an AddAnswerIndex(int index) to add an right answer to list. 

THis would be the better way maybe, because if you use property for lists too, the whole list content can be modified from outside always, which is not necssary.
And another benefit would be that you can write those methods like you need it. So do any kind of handling you need in there.

**Comment by mayisa87** [comment]
If you choose to go for the second option, to have special methods for adding and removing list entries, you could use a constructor to initalize your lists at the very beginning. 

Like

```
public Question()
{
  answerList = new List<string>();
  //etc. other stuff that needs to be done when object is created with the new operator
}
```

**Comment by mayisa87** [comment]
Here the loom ;) 
https://www.loom.com/share/472087719d034a36b884d973691a9982

**Comment by mayisa87** [comment]
After some again internal discussion, we agreed that like you are using your properties now is ok :)

See only issue #43 to make sure you are not using the {get;set;} , better use full property implementation to not lead into errors later on.

You asked, why you anyway use a property instead of a list. The reason, Michael explained it already, is, that in your property implementatoin you can later on add some special handling.

Imagine you would have your list defined as public like:
public List<string> myList = new List<string>();

It feels the same like using your property, BUT imagine you want to add a special handling like when getting your list, you want to do some output to a logging instance or whatever. This would mean, to again introduce a new property, set your field myList to private therefore, so you will need to change alllll occurances in code where you already used the public list field.

So it is way easier to implement from the start full methods like you already do it right with your lists.

Concerning the "read only", if you have no setter implemented, yes, from the outside it means, you can not replace the whole list simply, as there is no setter. That's right. Which is fully OK, as you can modify the elements anyway by accessing it via your property :)
