### ISSUE TITLE
itDoesnt better call it doesExist 

### ISSUE THREAD

**Issue by mayisa87** [CapioIM/P6QuizMaker#14]
https://github.com/CapioIM/P6QuizMaker/blob/d71a68266a3a40e3d3a599c542350c784bacaa94/P6QuizMaker/FileOperations.cs#L25

And switch the logic of the DoesFolderExist method, it is called "DoesFolderExist" so if it returns true, the folder should exist
In general when working with boolean, always try to use the positive formulation and avoid "not" in the naming, because if you got something like 
!doesNotExist
it is just mindblowing... this is a psychological thing I guess ;)

Recently when searching for something else, I found this webpage that explains a bit better (than me ;) ) why negative naming of variables is not the best you can do ;)

https://levelup.gitconnected.com/knot-of-nots-avoiding-negative-names-for-boolean-methods-641896a94a42#:~:text=The%20usual%20convention%20to%20name,exists().

**Comment by CapioIM** [comment]
What you said is 100% true
