### ISSUE TITLE
How to read user choices as integer, and convert to enum.

### ISSUE THREAD

**Issue by mayisa87** [CapioIM/P6QuizMaker#15]
https://github.com/CapioIM/P6QuizMaker/blob/5693aa7b6ccbc49432a7f33598379799add4195d/P6QuizMaker/UIMethods.cs#L47

As far as I see, you currently use the GetUserInput method always to get some user choice, which means, that there is also a range user can enter. And those choices you want to have stored as an enum too. 

So what you could do is, adding parameters to your method, like a min and max value, so you can additionally check, if the user enter a value in defined range. So when calling the method, depending on which kind of user choice (GameMode or QuizManipulationOptions etc.) you can give the right boundaries to it. 

For example 
`int newOrAmend = UIMethods.GetUserInputNum((int)Options.OptionChoice.Amend, (int)Options.OptionChoice.Remove); `

And as a next step, I would recommend to have separate methods in your UIMethods to handle your different enum inputs, which call this method above.

So you could have one method like 

"public static OptionChoice GetOptionChoice" Which will internally call this GetUserInputNum(min,max) and then if you have the right entered integer value, you can use a switch, to convert from your integer to your enum:

switch(userInput):
  case 1: 
     return Options.OptionChoice.Add;
  case 2: 

And this you could do for all kind of enums.

**Comment by CapioIM** [comment]
I think I got hang of it :) But I am not sure of it

**Comment by mayisa87** [comment]
https://github.com/CapioIM/P6QuizMaker/blob/5016d55f920a361c18214937059c9fc0f298aa6d/P6QuizMaker/Program.cs#L15-L17

Let the UI merhods return already the enum value and no longer an integer. So instead of using type cast (int) you will need to only use the enum values.

**Comment by mayisa87** [comment]
You can watch this live call recordinf, where another client had the same issue:

https://youtu.be/xmJycP74RF4?si=yYmVjZtlobgENHHr&t=2823

**Comment by CapioIM** [comment]
done it
