### ISSUE TITLE
Take care about naming

### ISSUE THREAD

**Issue by mayisa87** [CapioIM/P6QuizMaker#30]
https://github.com/CapioIM/P6QuizMaker/blob/f4f9a4b4c9fd99dab38708788bba96e3001c3f9a/P6QuizMaker/ManageQuestions.cs#L21

I know, you hate the naming stuff ;) but why do you call a question object,  QuizMaker? So first fix issue #28 and then check for better naming of the created objects to question or qnA

**Comment by CapioIM** [comment]
started with bad naming , and just ...... stayed consistent?
