### ISSUE TITLE
No need for first to be given as Parameter

### ISSUE THREAD

**Issue by mayisa87** [CapioIM/P6QuizMaker#32]
https://github.com/CapioIM/P6QuizMaker/blob/f4f9a4b4c9fd99dab38708788bba96e3001c3f9a/P6QuizMaker/ManageQuestions.cs#L68

If you want to do all your actions onnthe list within this class, you can have the List created in here, I see no reason to first create it in Main then? 

If you want to pass it back to Main for some reason later, better create it in this class and return it by return value

**Comment by CapioIM** [comment]
indeed
