### ISSUE TITLE
Do a break

### ISSUE THREAD

**Issue by mayisa87** [CapioIM/P6QuizMaker#34]
https://github.com/CapioIM/P6QuizMaker/blob/f4f9a4b4c9fd99dab38708788bba96e3001c3f9a/P6QuizMaker/ManageQuestions.cs#L86-L90

In case the user wants to exit anyway, you could just do a break or return statement instead of first setting all variables to false, which will cause the loop to exit anyway if you do a continue.

**Comment by CapioIM** [comment]
refactored
