### ISSUE TITLE
Move outside the switch after the if statement where the modification option is fetched

### ISSUE THREAD

**Issue by mayisa87** [CapioIM/P6QuizMaker#37]
https://github.com/CapioIM/P6QuizMaker/blob/f4f9a4b4c9fd99dab38708788bba96e3001c3f9a/P6QuizMaker/ManageQuestions.cs#L110-L113

Move this outside the if statement. Again like in issue #34 think about if a continue is what you need

And here you got the same again?
https://github.com/CapioIM/P6QuizMaker/blob/f4f9a4b4c9fd99dab38708788bba96e3001c3f9a/P6QuizMaker/ManageQuestions.cs#L135-L136

**Comment by CapioIM** [comment]
moved , and it is exactly what I need
