### ISSUE TITLE
Move to UI class

### ISSUE THREAD

**Issue by mayisa87** [CapioIM/P6QuizMaker#4]
https://github.com/CapioIM/P6QuizMaker/blob/2d8bbd498dd9ad851be19bb407f4ebb5d70b5385/P6QuizMaker/Logic.cs#L17-L24

**Comment by mayisa87** [comment]
Maybe this was too less explanation... Sorry for that. 

You should have one method in the UI class just asking user for the answerText and return it. So the method has a return type string.

and then in the Program.cs or in Logic you should add this text then to the list. 

this would be the clean way to do it and separate the logic and data best from each other :)

In general, always avoid to change input parameters, like in this case, your List. Try always to use input parameters only as information that you received and if you need to change something, try best to return it to calling method. If there are more things that need to be changed, better have more small methods then using the input parameters as variables to be changed

**Comment by CapioIM** [comment]
As I understood , store user input in variable and manipulate that variable?

**Comment by mayisa87** [comment]
Done with last commit
