### ISSUE TITLE
Better use full properties

### ISSUE THREAD

**Issue by mayisa87** [CapioIM/P6QuizMaker#43]
https://github.com/CapioIM/P6QuizMaker/blob/2de64bb3cb8eeda755fba54c4614990081eb8f32/P6QuizMaker/QuestionsAndAnswers.cs#L5

Better use the full property like you already implemented with your QuestionText, but no default {get; set;}

I discussed this also again internally :)Using the default {get; set} often can lead into errors if you want to later on change your code.
Same with only using a field as public field, and later on going to use it as Property.

So best is, to always use the prop full snipped and implement it fully like in this example:

![image](https://github.com/CapioIM/P6QuizMaker/assets/130921606/cefafa74-c779-4ad9-b873-7272694bc765)

**Comment by CapioIM** [comment]
refactored while ago, now I understand what you mean. I think
