### ISSUE TITLE
TIPP: Shorter way to write this code

### ISSUE THREAD

**Issue by mayisa87** [CapioIM/P6QuizMaker#50]
https://github.com/CapioIM/P6QuizMaker/blob/143979dfe7fc16bb48497766545016144e5033e5/P6QuizMaker/FileOperations.cs#L34-L41

Instead of using here an if and return true or false, you can do it like this:

return Directory.Exists(folderPath);

So just a general information. But... is this method necessary, you can simply call Directory.Exists(path) directly, as it is 1:1 the same? All you do here is, is to wrapp another method around it.

**Comment by CapioIM** [comment]
ok
