### ISSUE TITLE
Something missing here... check on answer input

### ISSUE THREAD

**Issue by mayisa87** [CapioIM/P6QuizMaker#6]
https://github.com/CapioIM/P6QuizMaker/blob/2d8bbd498dd9ad851be19bb407f4ebb5d70b5385/P6QuizMaker/Program.cs#L23-L26

When checking on the logic of "SetCorrectAnswerIndex" I was wondering if there is an easier way. And I recognized, that in Program.cs you call the DisplayTypeAnswerText, but you do no ReadLine after that? It is OK to combine user output and input in one method, so I would rather do a method like "GetAnwserText" and in there output "Type answer :" and immediately do the readline and return the given answer back.
So you could store this to a string variable. 

Instead of having this 
` correctAnswersIndexList.Add(AnswerList.LastIndexOf(AnswerList.Last()));`

You could have a counter that runs from 0 and increases for each answer, so you can add this counter/index as right answer index to the list, without this LastIndexOf and Last method calls. 

Or at least, if you first store the answer text to a string variable as mentioned above, you could use it then:
` correctAnswersIndexList.Add(AnswerList.LastIndexOf(myStoredAnswer));`

**Comment by CapioIM** [comment]
I was hesitant to make Method to do 2 things ....
