### ISSUE TITLE
Each enum can be a separate class file!

### ISSUE THREAD

**Issue by mayisa87** [CapioIM/P6QuizMaker#8]
https://github.com/CapioIM/P6QuizMaker/blob/726dce03c741e51c1a7745d0c2a2ce0d60ece952/P6QuizMaker/Enum.cs#L3

Usually in larger project, each enum is stored in a separte class file, and as data classes too, they are named with a noun. 

So for example, if you have a list of plantes stored in the enum, it will be called "Planets"
If you got a list of car modells it is called Modells or CarModells

If you got a list of vegetable names, it is called "Vegetables" or "VegetableTypes" maybe

**Comment by CapioIM** [comment]
ok

**Comment by CapioIM** [comment]
whatever I thought I might use it for , I don't need it any more :)
